/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uncuyo.proyecto.view;

import com.uncuyo.proyecto.controller.ClienteController;
import com.uncuyo.proyecto.controller.ReservaController;
import com.uncuyo.proyecto.model.Cliente;
import com.uncuyo.proyecto.model.Reserva;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReservaFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mendozaRemis = new javax.swing.JLabel();
        btRealizarR = new javax.swing.JButton();
        btModificarR = new javax.swing.JButton();
        btCancelarR = new javax.swing.JButton();
        btConsultarR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        mendozaRemis.setBackground(new java.awt.Color(255, 51, 153));
        mendozaRemis.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mendozaRemis.setForeground(new java.awt.Color(51, 153, 0));
        mendozaRemis.setText("MENDOZA REMIS");

        btRealizarR.setText("Realizar reserva");
        btRealizarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRealizarRMouseClicked(evt);
            }
        });

        btModificarR.setText("Modificar reserva");
        btModificarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btModificarRMouseClicked(evt);
            }
        });

        btCancelarR.setText("Cancelar reserva");
        btCancelarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarRActionPerformed(evt);
            }
        });

        btConsultarR.setText("Consultar reservas");
        btConsultarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultarRMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("¿Qué desear realizar?");

        btSalir.setText("Salir");
        btSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCancelarR)
                    .addComponent(btRealizarR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btModificarR)
                    .addComponent(btConsultarR))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mendozaRemis, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mendozaRemis, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRealizarR)
                    .addComponent(btModificarR))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelarR)
                    .addComponent(btConsultarR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarRActionPerformed
        CancelarReserva.main(new String[0]);
    }//GEN-LAST:event_btCancelarRActionPerformed

    private void btRealizarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRealizarRMouseClicked
        ReservaFrame.main(new String[0]); 
    }//GEN-LAST:event_btRealizarRMouseClicked

    private void btModificarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btModificarRMouseClicked
        ModificarReserva.main(new String[0]);
    }//GEN-LAST:event_btModificarRMouseClicked

    private void btConsultarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultarRMouseClicked
        Tablas.main(new String[0]);
    }//GEN-LAST:event_btConsultarRMouseClicked

    private void btSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirMouseClicked
        this.dispose(); 
    }//GEN-LAST:event_btSalirMouseClicked


    public static void main(String[] args) {
         // Crear una instancia de MainFrame
        MainFrame mainFrame = new MainFrame();
       
        
        // Configurar la operación de cierre de la ventana principal
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Mostrar la ventana principal
        mainFrame.setVisible(true);
        mainFrame.setLocationRelativeTo(null);
    }
    

    
    public Cliente setDatosCliente(String nombre, String dni,String celular, String ubicacion, Long cod_cliente){
        System.out.println(nombre + " - " + dni + " " + celular + " " + ubicacion );
        Cliente cliente = new Cliente(cod_cliente, dni, nombre, ubicacion, celular);
        clientectrl.insertarCliente(cliente);
        return cliente;
    }
    
    public void setDatosReserva(String destino, String fecha, String hora, long cod_reserva, long cod_cliente, Cliente cliente){
        // Convertir la fecha de tipo String a LocalDate
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate fechaReserva = LocalDate.parse(fecha, dateFormatter);

        // Convertir la hora de tipo String a LocalTime
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime horaReserva = LocalTime.parse(hora, timeFormatter);
        
        Reserva reserva = new Reserva(cod_reserva, destino, fechaReserva, horaReserva);
        reserva.setCliente(cliente);
        reservactrl.insertarReserva(reserva);
    }
   
    
    //private MainFrame mainframe;
    private final ReservaController reservactrl = new ReservaController();
    private final ClienteController clientectrl= new ClienteController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarR;
    private javax.swing.JButton btConsultarR;
    private javax.swing.JButton btModificarR;
    private javax.swing.JButton btRealizarR;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mendozaRemis;
    // End of variables declaration//GEN-END:variables
}
